server:
  port: ${EUREKA_CLIENT_PORT:9098}

spring:
  jpa:
    generate-ddl: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${services.bookmarkSvc-service.credentials.uri:http://127.0.0.1:8761}/bookmarkSvc/

---
spring:
  profiles: zipkin
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80