server:
  port: ${USER_SERVICE_PORT:9096}

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: ${services.bookmarkSvc-service.credentials.uri:http://127.0.0.1:8761}/eureka/
spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  cloud:
    config:
      uri: http://localhost:8888
management:
  security:
    enabled: false

---
spring:
  profiles: zipkin
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80