server:
  port: ${KRAKER_INFO_CONFIG_PORT:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${services.bookmarkSvc-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: config
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80