server:
  port: ${ZIPKIN_SERVICE_PORT:9411}

eureka:
  client:
    serviceUrl:
      defaultZone: ${services.registry.eureka.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: zipkin
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80