server:
  port: ${EUREKA_SERVICE_PORT:8761}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/bookmarkSvc/
  server:
    waitTimeInMsWhenSyncEmpty: 0