server:
  port: ${ZULL_SERVER_PORT:9093}

eureka:
  client:
    serviceUrl:
      defaultZone: ${services.bookmarkSvc-service.credentials.uri:http://127.0.0.1:8761}/eureka/
    registerWithEureka: false

zuul:
  prefix: /api
  routes:
    users:
      path: /userSvc/**
      serviceId: kraker-info-user-svc
#      stripPrefix: false

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80