server:
  port: ${ZULL_SERVER_PORT:9093}

eureka:
  client:
    serviceUrl:
      defaultZone: ${services.registry.eureka.uri:http://127.0.0.1:8761}/eureka/
    registerWithEureka: false

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80